import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { compile, type JSONSchema4 } from "json-schema-to-typescript";

type JsonObject = { [key: string]: JsonValue };
type JsonValue = JsonObject | JsonValue[] | boolean | number | string | null;

const desktopRoot = path.resolve(import.meta.dir, "..");
const repositoryRoot = path.resolve(desktopRoot, "..");
const generatedRoot = outputRoot();
const schemaPath = path.join(generatedRoot, "schema.json");

await mkdir(generatedRoot, { recursive: true });
await exportSchema();

const contract = parseObject(await readFile(schemaPath, "utf8"), "IPC contract");
await writeFile(
  path.join(generatedRoot, "types.ts"),
  await generateTypes(contract),
);
await writeFile(path.join(generatedRoot, "validators.ts"), generateValidators());

async function exportSchema(): Promise<void> {
  const process = Bun.spawn(
    [
      "cargo",
      "run",
      "-p",
      "kosmos-server",
      "--bin",
      "export-ipc-schema",
      "--",
      schemaPath,
    ],
    {
      cwd: repositoryRoot,
      stderr: "inherit",
      stdout: "inherit",
    },
  );
  if ((await process.exited) !== 0) {
    throw new Error("Rust IPC schema export failed");
  }
}

async function generateTypes(contract: JsonObject): Promise<string> {
  const definitions: JsonObject = {};
  const roots: string[] = [];

  for (const schema of actionSchemas(contract)) {
    addSchema(definitions, roots, schema);
  }
  for (const schema of notificationSchemas(contract)) {
    addSchema(definitions, roots, schema);
  }
  addSchema(definitions, roots, objectProperty(contract, "error"), "KosmosIpcError");

  const schema: JSONSchema4 = {
    $schema: "http://json-schema.org/draft-07/schema#",
    title: "KosmosIpcTypes",
    type: "object",
    properties: Object.fromEntries(
      roots.map((name) => [name, { $ref: `#/definitions/${name}` }]),
    ),
    definitions,
  };
  const declarations = await compile(schema, "KosmosIpcTypes", {
    additionalProperties: false,
    bannerComment: "// Generated by scripts/generate-ipc.ts. Do not edit.",
    unreachableDefinitions: true,
    unknownAny: true,
  });
  const domains = Object.keys(objectProperty(contract, "actions"));
  return `${declarations}\nexport type KosmosIpcDomain = ${domains.map((domain) => JSON.stringify(domain)).join(" | ")};
export type WorkspaceEditTransactionPhase = WorkspaceEditTransactionPhasePayload;
`;
}

function actionSchemas(contract: JsonObject): JsonObject[] {
  const actions = objectProperty(contract, "actions");
  return Object.values(actions).flatMap((domain) => {
    const domainActions = object(domain, "action domain");
    return Object.values(domainActions).flatMap((action) => {
      const actionSchema = object(action, "action contract");
      return [
        objectProperty(actionSchema, "params"),
        objectProperty(actionSchema, "result"),
      ];
    });
  });
}

function notificationSchemas(contract: JsonObject): JsonObject[] {
  return Object.values(objectProperty(contract, "notifications")).map((notification) =>
    object(notification, "notification contract"),
  );
}

function addSchema(
  definitions: JsonObject,
  roots: string[],
  schema: JsonObject,
  title = stringProperty(schema, "title"),
): void {
  const root = { ...schema };
  delete root.$schema;
  delete root.definitions;
  root.title = title;
  addDefinition(definitions, title, root);
  roots.push(title);

  const nestedDefinitions = schema.definitions;
  if (!nestedDefinitions) {
    return;
  }
  for (const [name, definition] of Object.entries(object(nestedDefinitions, "schema definitions"))) {
    addDefinition(definitions, name, definition);
  }
}

function addDefinition(definitions: JsonObject, name: string, definition: JsonValue): void {
  if (definitions[name]) {
    return;
  }
  definitions[name] = definition;
}

function generateValidators(): string {
  return `// Generated by scripts/generate-ipc.ts. Do not edit.
import Ajv, { type AnySchema, type ValidateFunction } from "ajv";
import contract from "./schema.json";

type JsonObject = Record<string, unknown>;

const ajv = new Ajv({ allErrors: false, logger: false, strict: false });
const actions = contract.actions as JsonObject;
const notifications = contract.notifications as JsonObject;
const resultValidators = validatorsForActions();
const notificationValidators = validatorsForNotifications();

export function validateActionResult(domain: string, action: string, value: unknown): boolean {
  const validator = resultValidators.get(key(domain, action));
  return Boolean(validator?.(value));
}

export function validateNotification(event: string, value: unknown): boolean {
  const validator = notificationValidators.get(event);
  return Boolean(validator?.(value));
}

function validatorsForActions(): Map<string, ValidateFunction> {
  const validators = new Map<string, ValidateFunction>();
  for (const [domain, domainActions] of Object.entries(actions)) {
    for (const [action, contract] of Object.entries(domainActions as JsonObject)) {
      validators.set(key(domain, action), ajv.compile((contract as JsonObject).result as AnySchema));
    }
  }
  return validators;
}

function validatorsForNotifications(): Map<string, ValidateFunction> {
  return new Map(
    Object.entries(notifications).map(([event, schema]) => [event, ajv.compile(schema as AnySchema)]),
  );
}

function key(domain: string, action: string): string {
  return domain + "." + action;
}
`;
}

function parseObject(value: string, description: string): JsonObject {
  return object(JSON.parse(value) as JsonValue, description);
}

function object(value: JsonValue | undefined, description: string): JsonObject {
  if (!value || Array.isArray(value) || typeof value !== "object") {
    throw new Error(`${description} must be an object`);
  }
  return value;
}

function objectProperty(value: JsonObject, property: string): JsonObject {
  return object(value[property], property);
}

function stringProperty(value: JsonObject, property: string): string {
  const propertyValue = value[property];
  if (typeof propertyValue !== "string") {
    throw new Error(`${property} must be a string`);
  }
  return propertyValue;
}

function outputRoot(): string {
  const outputIndex = Bun.argv.indexOf("--output");
  if (outputIndex === -1) {
    return path.join(desktopRoot, "src", "shared", "ipc", "generated");
  }
  const output = Bun.argv[outputIndex + 1];
  if (!output) {
    throw new Error("--output requires a directory");
  }
  return path.resolve(output);
}
