include!("parts/state_and_header.rs");
include!("parts/panels.rs");
include!("parts/branches_modal.rs");
include!("parts/branch_and_remote_modals.rs");
include!("parts/tags_and_stashes.rs");
include!("parts/modal_rows_and_buttons.rs");
include!("parts/change_tree.rs");
include!("parts/state_actions.rs");
include!("parts/async_actions.rs");
